### ISSUE TITLE
Integrate mio support

### ISSUE THREAD

**Issue by Kixunil** [rust-embedded/rust-sysfs-gpio#22]
I believe it would be beneficial to add support for mio (poll multiple FDs). This should be possible with conditional compilation.

**Comment by nastevens** [comment]
This should definitely be possible in mio 0.6, which has added the [`Evented`](https://docs.rs/mio/0.6.1/mio/trait.Evented.html) trait to allow custom implementations of asynchronous I/O. The actual implementation could be delegated to the underlying file descriptor. The most logical place in my mind to add this would be the `PinPoller` struct - adding a feature-enabled `impl` of `Evented`.

Is this something you're looking to take on @Kixunil? I've worked with mio before and would be happy to mentor if you have questions.

**Comment by Kixunil** [comment]
What's the advantage of having separate `PinPoller`? Is it setting correct interrupt? Also, I'm wondering how this could be integrated with Futures/Tokio.

I did try mio, so I know how to do and I'll be very happy to do it because it will improve one project I'm currently developing. However I have some  things to do, which have higher priority to me. Anyway, I expect I could implement it until Christmas. What do you think?

**Comment by pheki** [comment]
Hasn't this been fixed by #26?

**Comment by Kixunil** [comment]
@pheki yeah it was, I completely forgot about this issue. Thanks for ping.
