### ISSUE TITLE
Doesn't build on OSX

### ISSUE THREAD

**Issue by mnishizawa** [rust-embedded/rust-sysfs-gpio#28]
Trying to build this package locally on a Macbook and I get the following error:
```
error[E0432]: unresolved import `nix::sys::epoll::*`
  --> src/lib.rs:64:5
   |
64 | use nix::sys::epoll::*;
   |     ^^^^^^^^^^^^^^^^^^^ Could not find `epoll` in `nix::sys`
```

Version Info:
```
$ rustc --version
rustc 1.13.0

cargo 0.13.0 (eca9e15 2016-11-01)
```

**Comment by posborne** [comment]
The API that this libary is built around is the Linux kernel sysfs API, so it is not expected to work on other platforms.  That being said, I would accept a PR to support building a stub version on OSX or other platforms.  A similar change was contributed on another project: https://github.com/rust-embedded/rust-i2cdev/pull/22

Is this what you are looking to achieve or are you hoping for GPIOs under OSX.  I'm not aware of an API for doing that (not really the focal point for the OS).

**Comment by mnishizawa** [comment]
That makes sense.  Thanks!
