### ISSUE TITLE
Incompatible with tokio crate

### ISSUE THREAD

**Issue by kaojo** [rust-embedded/rust-sysfs-gpio#50]
Hi,

i want to use the PinValueStreams together with the newer version of tokio but if i try to use the API, I of course get the following compiler error: 
"expected struct `tokio_core::reactor::Handle`, found struct `tokio::reactor::Handle`"

For now I will just use the AsyncPinPoller and construct the PinValueStream myself. Would it be possible to add support for the "tokio" crate and remain backwards compatibility ?

**Comment by nastevens** [comment]
The `tokio` crate is the new standard way of interacting with Tokio, and I believe that the API is meant to be stable until it migrates to `futures > 0.1`. @kaojo if you want to take a crack at a PR for updating to use `tokio` directly, I think it would be valuable.

**Comment by vlvrd** [comment]
@kaojo @nastevens hi, I think this issue should be closed. :space_invader:
