### ISSUE TITLE
Tokio doesn't support Rust 1.21.0

### ISSUE THREAD

**Issue by vlvrd** [rust-embedded/rust-sysfs-gpio#53]
I noticed your build was broken and read that Tokio doesn't support Rust 1.21.0 (https://github.com/tokio-rs/tokio#supported-rust-versions), so the build breaks when compiling lazy_static (https://travis-ci.org/rust-embedded/rust-sysfs-gpio/jobs/485192256).

Should the Rust version be updated? I can help you test a new minimum version.

**Comment by posborne** [comment]
@vlvrd Absolutely, contributions would be very welcome.
