### ISSUE TITLE
Migrate to tokio 1.x

### ISSUE THREAD

**Issue by eldruin** [rust-embedded/rust-sysfs-gpio#68]
Since the kernels supporting only this interface and not `gpio-cdev` will continue with us "forever", it would be great to give this crate a revamp and migrate it to tokio 1.x.
However, I do not have the know-how to do this.
Could somebody help us here?
Maybe @benjumanji, @oll3 or somebody else?

Over at `gpio-cdev` is an example of the migration: https://github.com/rust-embedded/gpio-cdev/pull/55

**Comment by oll3** [comment]
Hi @eldruin ! Took a stab at it in #69 since looked similar to the gpio-cdev tokio bump :crab:

**Comment by eldruin** [comment]
Awesome @oll3! thank you!

**Comment by eldruin** [comment]
Fixed in #69. Thank you!
